name: Build PR

on:
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/*.cmake'
      - '**/CMakelists.txt'

jobs:
  Formatting:
    name: Check Formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: novelrt/setup-cpp@v1

      - name: Check formatting via clang-format
        shell: bash
        run: |
          buildDir="$(pwd)/build"
          legacySrcDir="$(pwd)/LegacySrc"
          artefactsDir="$(pwd)/artefacts"
          find "$(pwd)" \( -path "$buildDir" -o -path "$legacySrcDir" -o -path "$artefactsDir" \) -prune -o \
            -name '*.cpp' -o -name '*.hpp' -exec clang-format --dry-run --Werror --style=file '{}' \+

      - name: Preinstall dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install libglm-dev cmake libxcb-dri3-0 libxcb-present0 \
            libpciaccess0 libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev \
            libx11-dev libwayland-dev libxrandr-dev libxcb-randr0-dev \
            libxcb-ewmh-dev git python-is-python3 bison libx11-xcb-dev \
            libxcursor-dev libxi-dev libxinerama-dev libxkbcommon-dev \
            libxext-dev liblz4-dev libzstd-dev ocaml-core ninja-build \
            pkg-config libxml2-dev wayland-protocols python3-jsonschema \
            clang-format qtbase5-dev qt6-base-dev

          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 20
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 10

          sudo update-alternatives --set cc /usr/bin/clang
          sudo update-alternatives --set c++ /usr/bin/clang++

      - uses: novelrt/setup-vulkan@v2
        with:
          version: 1.4.313.0

      - name: Generate build system
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_CLANG_TIDY="clang-tidy --config-file=.clang-tidy -p build" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build NovelRT with Clang-Tidy
        run: cmake --build build --config Debug --parallel

  Build:
    name: ${{ matrix.os }} - ${{ matrix.configuration }} - Vulkan ${{ matrix.vulkan }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, RelWithDebInfo]
        os: [windows-2025, ubuntu-24.04, macos-15]
        vulkan: [1.4.313.0]

    steps:
      - name: Preinstall dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install libglm-dev cmake libxcb-dri3-0 libxcb-present0 \
            libpciaccess0 libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev \
            libx11-dev libwayland-dev libxrandr-dev libxcb-randr0-dev \
            libxcb-ewmh-dev git python-is-python3 bison libx11-xcb-dev \
            libxcursor-dev libxi-dev libxinerama-dev libxkbcommon-dev \
            libxext-dev liblz4-dev libzstd-dev ocaml-core ninja-build \
            pkg-config libxml2-dev wayland-protocols python3-jsonschema \
            clang-format qtbase5-dev qt6-base-dev

          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 20
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 10

          sudo update-alternatives --set cc /usr/bin/clang
          sudo update-alternatives --set c++ /usr/bin/clang++

      - uses: actions/checkout@v4

      - uses: novelrt/setup-cpp@v1
      - uses: novelrt/setup-vulkan@v2
        with:
          version: ${{ matrix.vulkan }}

      - name: Restore incremental build artefacts
        id: cache
        uses: actions/cache@v4
        with:
          path: build
          key: pr${{ github.event.number }}-${{ matrix.os }}-${{ matrix.configuration }}-vk${{ matrix.vulkan }}

      - name: Setup Visual Studio Developer Command Prompt
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          $vsWhere = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $installationPath = & $vsWhere -prerelease -latest -property installationPath
          if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
            & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo && set" | foreach-object {
              $name, $value = $_ -split '=', 2
              $currentValue = if (Test-Path -Path "env:\$name") { (Get-Item -Path "env:\$name").Value } else { $null }
              if ($value -ne $currentValue) {
                if ($name -eq 'PATH') {
                  echo "$value" >> "${Env:GITHUB_PATH}"
                } else {
                  echo "$name=$value" >> "${Env:GITHUB_ENV}"
                }
              }
            }
          }

      - name: Generate build system
        if: steps.cache.outputs.cache-hit != 'true'
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build NovelRT
        run: cmake --build build --config ${{ matrix.configuration }} --parallel
      - name: Install NovelRT
        run: cmake --install build --config ${{ matrix.configuration }} --prefix artefacts

      - name: Publish build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.configuration }}-vk${{ matrix.vulkan }}
          path: artefacts
