name: Build PR

on:
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/*.cmake'
      - '**/CMakelists.txt'

jobs:
  Formatting:
    name: Check Formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting via clang-format
        shell: bash
        run: |
          buildDir="$(pwd)/build"
          legacySrcDir="$(pwd)/LegacySrc"
          artefactsDir="$(pwd)/artefacts"
          find "$(pwd)" \( -path "$buildDir" -o -path "$legacySrcDir" -o -path "$artefactsDir" \) -prune -o \
            -name '*.cpp' -o -name '*.hpp' -exec clang-format --dry-run --Werror --style=file '{}' \+

  Build:
    name: ${{ matrix.os }} - ${{ matrix.configuration }} - Vulkan ${{ matrix.vulkan }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, RelWithDebInfo]
        os: [windows-2025, ubuntu-24.04, macos-15]
        vulkan: [1.4.313.0]

    steps:
      - uses: novelrt/setup-vulkan@v1.10
        with:
          version: ${{ matrix.vulkan }}

      - uses: novelrt/setup-cpp@v1
      - uses: actions/checkout@v4

      - name: Restore incremental build artefacts
        id: cache
        uses: actions/cache@v4
        with:
          path: build
          key: pr${{ github.event.number }}-${{ matrix.os }}-${{ matrix.configuration }}-vk${{ matrix.vulkan }}

      - name: Generate build system
        if: steps.cache.output.cache-hit != 'true'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} \
            -DCMAKE_CXX_CLANG_TIDY="clang-tidy --config-file=.clang-tidy -p build" \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build NovelRT
        run: |
          cmake --build build --config ${{ matrix.configuration }} --parallel
          cmake --install build --config ${{ matrix.configuration }} --parallel --prefix artefacts

      - name: Publish build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.configuration }}-vk${{ matrix.vulkan }}
          path: artefacts
