name: Continuous Integration

on:
  pull_request:

jobs:
  CI_Ubuntu:
    name: Ubuntu_${{ matrix.configuration }}_x64
    runs-on: ubuntu-latest
    container:
      image: novelrt/novelrt-build:latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run CI Build Script
        run: scripts/cibuild.sh --configuration ${{ matrix.configuration }}

  CI_Windows:
    name: Windows_${{ matrix.configuration }}_x64
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Windows Setup
        run: scripts/machine-setup.cmd

      - name: Run CI Build Script
        id: build
        run: scripts/cibuild.cmd -configuration ${{ matrix.configuration }}

  Formatting:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2

      - name: Check Formatting
        id: formatting
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: 'src tests include samples'
          extensions: 'h,cpp,c,hpp'
          clangFormatVersion: 10
          inplace: True
          style: file

      - name: Confirm Results
        id: results
        run: scripts/ci-checkdiff.sh

      - name: Upload Patch
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: clang-format-patch
          path: artifacts/clang-format.patch
